### ISSUE TITLE
Vocab and npz files format

### ISSUE THREAD

**Issue by un-lock-me** [awslabs/w-lda#7]
Hello,

First of all, thanks so much for sharing the code. However, it is difficult to use the code as there are minimum information on how to prepare the data. I would appreciate it if you can share the format of `vocab` and `npz files` with us. As currently Im not able to run the code on a dataset similar to Yelp. I guess there may be something wrong with the format of my data.

**Comment by un-lock-me** [comment]
@fnan Any help here?

**Comment by un-lock-me** [comment]
I did not find any section for the preprocessing steps you taken. I appreciate it if you could share the format with us or at least share the preprocessing step you have used.

**Comment by un-lock-me** [comment]
To make my question more clear, did you pass the document based on the position of the vocal in each document or the frequency, or frequency +normalization?

**Comment by fnan** [comment]
Hi, 
Could you follow the example mentioned in the `README` about `Wikitext-103` for data preparation? In particular, the script  `examples/domains/wikitext103_wae.py` has code to make `vocab` and `npz` files https://github.com/awslabs/w-lda/blob/master/examples/domains/wikitext103_wae.py#L177-L183

**Comment by un-lock-me** [comment]
@fnan Thanks so much. I was trying to do similar thing but thanks for highlighting the script. I still have  not got it to work. By any chance do you have the script of preprocessing for the Yelp data? My data is similar to Yelp dataset I want to check which part I am doing it incorrectly.  I really appreciate it.

**Comment by un-lock-me** [comment]
I think Im clear now where the problem was. Just want to make sure that I understood the code correctly. While preparing the wiki document you treat each line of each document as one of the element of the list (or each line is a document instead of the whole document itself) Am I correct? if so, did you do the same for other datasets?

Appreciate it if you can spend some time and clarify this for me. Thanks :) @fnan .

**Comment by fnan** [comment]
Each element of the [train_doc_list](https://github.com/awslabs/w-lda/blob/15eb320faac0570e858c689df6f2c61bcad3010e/examples/domains/wikitext103_wae.py#L128) should be a whole document. In wikitext103, a document is broken into multiple lines in the input file. The `token_list_per_doc` function chunks the input lines into documents.
